// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdjftpoapzbrzzcwguxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkamZ0cG9hcHpicnp6Y3dndXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTM0MzgsImV4cCI6MjA2MDE4OTQzOH0.MMeaHibKlIRlEkkNHoKMobOlEmO8gcEqhMM5sIyOpp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);